# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b22ec1069ab8304309622aefbe61194001fa44b811bbc857c07be37c905beeeed749135f2c5a9cd2975bcc3d0f968e5605be9ac654f4746c207db98f079a9829

test:
  secret_key_base: 2aaee1c2f6c72a839041eb8ebedec4274d30e68d4832450e05020c1190510d243d78c5f5083897d1af874075b74dfe1ef53bfa3a83d4b8896cbbcd384bc01cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
